server:
  port: 8082
spring:
  application:
    name: "crediyarequest"
  devtools:
    add-properties: false
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "crediya_request"
    schema: "public"
    username: "crediya"
    password: "crediya"

springdoc:
  swagger-ui:
    url: /openapi/openapi.yaml

api:
  base-path: "/api"
  version: "/v1"